---
# SPDX-FileCopyrightText: © 2021 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: CC0-1.0

name: Continuous Integration

"on":
  - "push"
  - "pull_request"

permissions:
  contents: read
  pull-requests: read

env:
  npm_config_cache: /tmp/npm-cache

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Use Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run linter tests
        run: npm run lint

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          # Support policy: We support every Node.js version that is still "maintained".
          # See: https://nodejs.org/en/about/releases/
          - "20.x"
          - "22.x"
          - "24.x"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - id: npm-cache
        name: Restore npm cache
        uses: actions/cache@v4
        with:
          key: npm-cache-${{ github.ref_name }}
          path: ${{ env.npm_config_cache }}
      - name: Install dependencies
        run: make dependencies-get
      - name: Run full test suite
        run: make check-full
